#pragma once

/**
 * @brief Umbrella header for SnAPI.GameFramework.
 * @remarks Include this to access the full public API surface.
 */
#include "Assert.h"
#include "BuiltinTypes.h"
#include "AudioListenerComponent.h"
#include "AudioSourceComponent.h"
#include "AudioSystem.h"
#include "CharacterMovementController.h"
#include "CameraComponent.h"
#include "CollisionFilters.h"
#include "ColliderComponent.h"
#include "ComponentStorage.h"
#include "DirectionalLightComponent.h"
#include "Expected.h"
#include "FollowTargetComponent.h"
#include "GameplayHost.h"
#include "GameplayRpcGateway.h"
#include "GameRuntime.h"
#include "Handle.h"
#include "BaseComponent.h"
#include "IGame.h"
#include "IGameMode.h"
#include "IGameService.h"
#include "InputComponent.h"
#include "InputSystem.h"
#include "UISystem.h"
#include "UIPropertyPanel.h"
#include "UIRenderViewport.h"
#include "IWorld.h"
#include "JobSystem.h"
#include "Level.h"
#include "LocalPlayer.h"
#include "LocalPlayerService.h"
#include "Math.h"
#include "Level.h"
#include "ObjectPool.h"
#include "NetReplication.h"
#include "NetRpc.h"
#include "NetworkSystem.h"
#include "PhysicsSystem.h"
#include "RendererSystem.h"
#include "Relevance.h"
#include "Reflection.h"
#include "RigidBodyComponent.h"
#include "SkeletalMeshComponent.h"
#include "StaticMeshComponent.h"
#include "Serialization.h"
#include "ScriptABI.h"
#include "ScriptBindings.h"
#include "ScriptComponent.h"
#include "ScriptEngine.h"
#include "TransformComponent.h"
#include "TypeAutoRegistration.h"
#include "TypeRegistration.h"
#include "Uuid.h"
#include "World.h"
#include "WorldEcsRuntime.h"

#include "AssetPipelineFactories.h"
#include "AssetPipelineIds.h"
#include "AssetPipelineSerializers.h"
