#pragma once

/**
 * @brief Umbrella header for SnAPI.GameFramework.
 * @remarks Include this to access the full public API surface.
 */
#include "Assert.h"
#include "BuiltinTypes.h"
#include "AudioListenerComponent.h"
#include "AudioSourceComponent.h"
#include "AudioSystem.h"
#include "CharacterMovementController.h"
#include "CameraComponent.h"
#include "CollisionFilters.h"
#include "ColliderComponent.h"
#include "ComponentStorage.h"
#include "Expected.h"
#include "GameRuntime.h"
#include "Handle.h"
#include "IComponent.h"
#include "ILevel.h"
#include "INode.h"
#include "InputComponent.h"
#include "InputSystem.h"
#include "IWorld.h"
#include "JobSystem.h"
#include "Level.h"
#include "Math.h"
#include "NodeGraph.h"
#include "ObjectPool.h"
#include "NetReplication.h"
#include "NetRpc.h"
#include "NetworkSystem.h"
#include "PhysicsSystem.h"
#include "RendererSystem.h"
#include "Relevance.h"
#include "Reflection.h"
#include "RigidBodyComponent.h"
#include "SkeletalMeshComponent.h"
#include "StaticMeshComponent.h"
#include "Serialization.h"
#include "ScriptABI.h"
#include "ScriptBindings.h"
#include "ScriptComponent.h"
#include "ScriptEngine.h"
#include "TransformComponent.h"
#include "TypeAutoRegistration.h"
#include "TypeRegistration.h"
#include "Uuid.h"
#include "World.h"

#include "AssetPipelineFactories.h"
#include "AssetPipelineIds.h"
#include "AssetPipelineSerializers.h"
