include_guard(GLOBAL)

function(snapi_add_reflection_codegen)
    if (NOT SNAPI_GF_BUILD_REFLECTION_GEN)
        return()
    endif()

    set(options)
    set(oneValueArgs TARGET OUTPUT SEED_SOURCE BUILD_DIR PROJECT_ROOT HEADER_ROOT GENERATED_INCLUDE_DIR GENERATED_SOURCE_DIR)
    set(multiValueArgs HEADERS EXTRA_ARGS)
    cmake_parse_arguments(SNAPI_REFLECT "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    if (NOT SNAPI_REFLECT_TARGET)
        message(FATAL_ERROR "snapi_add_reflection_codegen requires TARGET")
    endif()
    if (NOT SNAPI_REFLECT_OUTPUT)
        message(FATAL_ERROR "snapi_add_reflection_codegen requires OUTPUT")
    endif()
    if (NOT SNAPI_REFLECT_SEED_SOURCE)
        message(FATAL_ERROR "snapi_add_reflection_codegen requires SEED_SOURCE")
    endif()
    if (NOT SNAPI_REFLECT_BUILD_DIR)
        message(FATAL_ERROR "snapi_add_reflection_codegen requires BUILD_DIR")
    endif()
    if (NOT SNAPI_REFLECT_PROJECT_ROOT)
        set(SNAPI_REFLECT_PROJECT_ROOT "${CMAKE_SOURCE_DIR}")
    endif()
    if (NOT SNAPI_REFLECT_HEADER_ROOT)
        message(FATAL_ERROR "snapi_add_reflection_codegen requires HEADER_ROOT")
    endif()
    if (NOT SNAPI_REFLECT_GENERATED_INCLUDE_DIR)
        message(FATAL_ERROR "snapi_add_reflection_codegen requires GENERATED_INCLUDE_DIR")
    endif()
    if (NOT SNAPI_REFLECT_GENERATED_SOURCE_DIR)
        set(SNAPI_REFLECT_GENERATED_SOURCE_DIR "${CMAKE_CURRENT_BINARY_DIR}/reflection/src")
    endif()

    set(SNAPI_REFLECT_OUTPUT_PATH "${SNAPI_REFLECT_OUTPUT}")
    if (NOT IS_ABSOLUTE "${SNAPI_REFLECT_OUTPUT_PATH}")
        set(SNAPI_REFLECT_OUTPUT_PATH "${CMAKE_CURRENT_BINARY_DIR}/${SNAPI_REFLECT_OUTPUT_PATH}")
    endif()

    set(SNAPI_REFLECT_GENERATED_INCLUDE_PATH "${SNAPI_REFLECT_GENERATED_INCLUDE_DIR}")
    if (NOT IS_ABSOLUTE "${SNAPI_REFLECT_GENERATED_INCLUDE_PATH}")
        set(SNAPI_REFLECT_GENERATED_INCLUDE_PATH "${CMAKE_CURRENT_BINARY_DIR}/${SNAPI_REFLECT_GENERATED_INCLUDE_DIR}")
    endif()

    set(SNAPI_REFLECT_GENERATED_SOURCE_PATH "${SNAPI_REFLECT_GENERATED_SOURCE_DIR}")
    if (NOT IS_ABSOLUTE "${SNAPI_REFLECT_GENERATED_SOURCE_PATH}")
        set(SNAPI_REFLECT_GENERATED_SOURCE_PATH "${CMAKE_CURRENT_BINARY_DIR}/${SNAPI_REFLECT_GENERATED_SOURCE_DIR}")
    endif()

    set(SNAPI_REFLECT_GENERATED_SOURCES)
    foreach(SNAPI_REFLECT_HEADER IN LISTS SNAPI_REFLECT_HEADERS)
        if (IS_ABSOLUTE "${SNAPI_REFLECT_HEADER}")
            file(RELATIVE_PATH SNAPI_REFLECT_HEADER_REL "${SNAPI_REFLECT_HEADER_ROOT}" "${SNAPI_REFLECT_HEADER}")
            if (SNAPI_REFLECT_HEADER_REL MATCHES "^\\.\\.")
                get_filename_component(SNAPI_REFLECT_HEADER_REL "${SNAPI_REFLECT_HEADER}" NAME)
            endif()
        else()
            set(SNAPI_REFLECT_HEADER_REL "${SNAPI_REFLECT_HEADER}")
        endif()

        set(SNAPI_REFLECT_GENERATED_SOURCE_REL "${SNAPI_REFLECT_HEADER_REL}.generated.cpp")
        list(APPEND SNAPI_REFLECT_GENERATED_SOURCES
            "${SNAPI_REFLECT_GENERATED_SOURCE_PATH}/${SNAPI_REFLECT_GENERATED_SOURCE_REL}")
    endforeach()

    get_filename_component(SNAPI_REFLECT_OUTPUT_NAME_WE "${SNAPI_REFLECT_OUTPUT_PATH}" NAME_WE)
    get_filename_component(SNAPI_REFLECT_OUTPUT_NAME "${SNAPI_REFLECT_OUTPUT_PATH}" NAME)
    set(SNAPI_REFLECT_GENERATED_TYPE_NAME_HEADER_PATH
        "${SNAPI_REFLECT_GENERATED_INCLUDE_PATH}/${SNAPI_REFLECT_OUTPUT_NAME_WE}.typenames.generated.hpp")
    get_filename_component(SNAPI_REFLECT_GENERATED_TYPE_NAME_HEADER_NAME
        "${SNAPI_REFLECT_GENERATED_TYPE_NAME_HEADER_PATH}" NAME)
    string(REGEX REPLACE "[^A-Za-z0-9_]" "_" SNAPI_REFLECT_MANIFEST_SYMBOL_SUFFIX "${SNAPI_REFLECT_OUTPUT_NAME}")
    set(SNAPI_REFLECT_MANIFEST_SYMBOL "SnAPI_LinkReflectionAnchors_${SNAPI_REFLECT_MANIFEST_SYMBOL_SUFFIX}")

    set(SNAPI_REFLECT_STAMP_PATH "${SNAPI_REFLECT_OUTPUT_PATH}.stamp")

    set(SNAPI_REFLECT_EXTRA_ARG_FLAGS)
    foreach(SNAPI_REFLECT_ARG IN LISTS SNAPI_REFLECT_EXTRA_ARGS)
        list(APPEND SNAPI_REFLECT_EXTRA_ARG_FLAGS --extra-arg "${SNAPI_REFLECT_ARG}")
    endforeach()

    add_custom_command(
        OUTPUT "${SNAPI_REFLECT_OUTPUT_PATH}" "${SNAPI_REFLECT_STAMP_PATH}" ${SNAPI_REFLECT_GENERATED_SOURCES}
        COMMAND ${CMAKE_COMMAND} -E make_directory "$<SHELL_PATH:${CMAKE_CURRENT_BINARY_DIR}>"
        COMMAND ${CMAKE_COMMAND} -E make_directory "$<SHELL_PATH:${SNAPI_REFLECT_GENERATED_INCLUDE_PATH}>"
        COMMAND ${CMAKE_COMMAND} -E make_directory "$<SHELL_PATH:${SNAPI_REFLECT_GENERATED_SOURCE_PATH}>"
        COMMAND $<TARGET_FILE:SnAPI.GameFramework.ReflectionGen>
            --output "$<SHELL_PATH:${SNAPI_REFLECT_OUTPUT_PATH}>"
            --build-dir "$<SHELL_PATH:${SNAPI_REFLECT_BUILD_DIR}>"
            --seed-source "$<SHELL_PATH:${SNAPI_REFLECT_SEED_SOURCE}>"
            --project-root "$<SHELL_PATH:${SNAPI_REFLECT_PROJECT_ROOT}>"
            --header-root "$<SHELL_PATH:${SNAPI_REFLECT_HEADER_ROOT}>"
            --generated-include-dir "$<SHELL_PATH:${SNAPI_REFLECT_GENERATED_INCLUDE_PATH}>"
            --generated-source-dir "$<SHELL_PATH:${SNAPI_REFLECT_GENERATED_SOURCE_PATH}>"
            --generated-type-name-header "$<SHELL_PATH:${SNAPI_REFLECT_GENERATED_TYPE_NAME_HEADER_PATH}>"
            ${SNAPI_REFLECT_EXTRA_ARG_FLAGS}
            ${SNAPI_REFLECT_HEADERS}
        COMMAND ${CMAKE_COMMAND} -E touch "$<SHELL_PATH:${SNAPI_REFLECT_STAMP_PATH}>"
        DEPENDS
            SnAPI.GameFramework.ReflectionGen
            "${SNAPI_REFLECT_SEED_SOURCE}"
            ${SNAPI_REFLECT_HEADERS}
        VERBATIM
    )

    set_source_files_properties("${SNAPI_REFLECT_OUTPUT_PATH}" PROPERTIES GENERATED TRUE)
    set_source_files_properties("${SNAPI_REFLECT_GENERATED_TYPE_NAME_HEADER_PATH}" PROPERTIES GENERATED TRUE)
    set_source_files_properties(${SNAPI_REFLECT_GENERATED_SOURCES} PROPERTIES GENERATED TRUE)
    target_sources(${SNAPI_REFLECT_TARGET} PRIVATE "${SNAPI_REFLECT_OUTPUT_PATH}" ${SNAPI_REFLECT_GENERATED_SOURCES})
    target_include_directories(${SNAPI_REFLECT_TARGET} PUBLIC "$<BUILD_INTERFACE:${SNAPI_REFLECT_GENERATED_INCLUDE_PATH}>")
    target_compile_definitions(${SNAPI_REFLECT_TARGET}
        PRIVATE
            "SNAPI_REFLECTION_LINK_ANCHOR_SYMBOL=${SNAPI_REFLECT_MANIFEST_SYMBOL}")
    if (MSVC)
        target_compile_options(${SNAPI_REFLECT_TARGET}
            PUBLIC
                "$<$<COMPILE_LANGUAGE:CXX>:/FI${SNAPI_REFLECT_GENERATED_TYPE_NAME_HEADER_NAME}>")
    else()
        target_compile_options(${SNAPI_REFLECT_TARGET}
            PUBLIC
                "$<$<COMPILE_LANGUAGE:CXX>:SHELL:-include ${SNAPI_REFLECT_GENERATED_TYPE_NAME_HEADER_NAME}>")
    endif()

    set(SNAPI_REFLECT_CODEGEN_TARGET "${SNAPI_REFLECT_TARGET}.ReflectionGenerated")
    if (NOT TARGET "${SNAPI_REFLECT_CODEGEN_TARGET}")
        add_custom_target("${SNAPI_REFLECT_CODEGEN_TARGET}" DEPENDS "${SNAPI_REFLECT_STAMP_PATH}")
    endif()
    add_dependencies(${SNAPI_REFLECT_TARGET} "${SNAPI_REFLECT_CODEGEN_TARGET}")
endfunction()
